### ISSUE TITLE
unknown file format(magic number)

### ISSUE THREAD

**Issue by ZenXYZ** [caoqianli/pcap-parser#21]
My pcap(from tcpdump) file can be opened by wireshark,
but show "unknown file format" while using pcap-parser.

I found that the magic number of my pcap file is "A1B2C3D4"(using 010editor to open it)
which is mentioned valid in the wireshark document,
[https://wiki.wireshark.org/Development/LibpcapFileFormat#File_Format](url)

PS: 
1.other pcap file start with D4C3B2A1 works fine.
2.I tried to bypass it by simply edited parse_pcap.py and add `magic_num == D4C3B2A1` , I got a `"Can't recognize this PCAP file format."` exception.

**Comment by caoqianli** [comment]
@ZenXYZ A new version 0.5.9 is just released, should fix this bug.

**Comment by ZenXYZ** [comment]
yes, it works, thanks for the quick fix
